# Generated by Django 4.1 on 2022-10-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppQatar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copas',
            old_name='selecc',
            new_name='selección',
        ),
    ]
