# Generated by Django 4.1 on 2022-10-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppQatar', '0002_rename_selecc_copas_selección'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copas',
            old_name='selección',
            new_name='selecc',
        ),
    ]
