# Generated by Django 4.1 on 2022-10-08 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppQatar', '0007_seleccion_autor_alter_copas_ultimacopa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seleccion',
            old_name='autor',
            new_name='author',
        ),
    ]
