# Generated by Django 4.1 on 2022-10-08 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppQatar', '0008_rename_autor_seleccion_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seleccion',
            name='author',
        ),
    ]
