# Generated by Django 4.1 on 2022-10-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppQatar', '0009_remove_seleccion_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='seleccion',
            name='autor',
            field=models.CharField(default='', max_length=40),
        ),
    ]
