# Generated by Django 4.1 on 2022-10-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppQatar', '0010_seleccion_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seleccion',
            name='autor',
        ),
    ]
