# Generated by Django 4.1 on 2022-10-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppQatar', '0014_remove_copas_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copas',
            name='ultimaCopa',
            field=models.DateField(verbose_name='Última copa conseguida'),
        ),
    ]
