# Generated by Django 4.1 on 2022-10-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppQatar', '0015_alter_copas_ultimacopa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copas',
            name='ultimaCopa',
            field=models.IntegerField(verbose_name='Última copa conseguida'),
        ),
    ]
