# Generated by Django 4.1 on 2022-10-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppQatar', '0016_alter_copas_ultimacopa'),
    ]

    operations = [
        migrations.AddField(
            model_name='seleccion',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
