# Generated by Django 4.1 on 2022-10-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppQatar', '0017_seleccion_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(default='', max_length=40)),
                ('ganadora', models.CharField(max_length=40)),
                ('segunda', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='copas',
            name='ultimaCopa',
            field=models.IntegerField(verbose_name='Año de la última copa conseguida ("0" si no ha ganado aún)'),
        ),
        migrations.AlterField(
            model_name='seleccion',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de su primer partido (YYYY-MM-DD)'),
        ),
    ]
