# Generated by Django 4.1 on 2022-10-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppQatar', '0018_prediccion_alter_copas_ultimacopa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediccion',
            name='hoy',
            field=models.DateField(blank=True, null=True),
        ),
    ]
