# Generated by Django 4.1 on 2022-10-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppQatar', '0020_alter_prediccion_hoy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccion',
            name='hoy',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
