# Generated by Django 4.1 on 2022-10-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppQatar', '0021_alter_prediccion_hoy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccion',
            name='ganadora',
            field=models.CharField(max_length=40, verbose_name='Selección campeona'),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='segunda',
            field=models.CharField(max_length=40, verbose_name='Selección subcampeona'),
        ),
    ]
