# Generated by Django 4.1 on 2022-10-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppQatar', '0022_alter_prediccion_ganadora_alter_prediccion_segunda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccion',
            name='hoy',
            field=models.DateTimeField(blank=True, max_length=40, null=True),
        ),
    ]
