# Generated by Django 4.1 on 2022-10-12 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppQatar', '0023_alter_prediccion_hoy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccion',
            name='hoy',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
